"""add_phone_field_to_users_table

Revision ID: 4868126f3dd0
Revises: d6547f159c46
Create Date: 2025-07-19 05:35:27.712491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '4868126f3dd0'
down_revision = 'd6547f159c46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    indexes = [ix['name'] for ix in inspector.get_indexes('users')]
    if 'ix_users_username' in indexes:
        op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ### 