"""Rename adress to address in users table

Revision ID: 6650f21c2ed1
Revises: ffdc869c0290
Create Date: 2025-07-15 02:36:57.654669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6650f21c2ed1'
down_revision = 'ffdc869c0290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('users', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'address')
    # ### end Alembic commands ### 